on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n daprcalc -g daprcalca404-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n daprcalc --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n daprcalc --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n daprcalc --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: daprcalc.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/2.hello-kubernetes/node" -f  "2.hello-kubernetes/node/Dockerfile" -t daprcalc.azurecr.io/daprclac:${{ github.sha }}
        docker push daprcalc.azurecr.io/daprclac:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_daprclac_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep daprclaca53a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace daprclaca53a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: daprclaca53a
        container-registry-url: daprcalc.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: daprclacdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: daprclaca53a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          daprcalc.azurecr.io/daprclac:${{ github.sha }}
        imagepullsecrets: |
          daprclacdockerauth